### ISSUE TITLE
Add the London Baptist Confession (1689)

### ISSUE THREAD

**Issue by mattrob33** [json469/sound_doctrine#9]
Again, I would be willing to do the work and submit a pull request. Just checking to see if this is one you would approve. The LBC is essentially a Baptist revision of the WCF and is used the the statement of faith for many Reformed Baptist churches today.

**Comment by json469** [comment]
Yes please! I am more than happy to add this. Although I might have to put some time to fully read it. I think I remember glancing through the one that C.H. Spurgeon has revised. Thank you for your contribution and also please let me know if you need any help from my side.

**Comment by json469** [comment]
Closed at #12
